### ISSUE TITLE
Do we really want all lower case request headers?

### ISSUE THREAD

**Issue by joshski** [featurist/httpism#7]
When we forget to use lower case request headers, e.g:

```JavaScript
httpism.get('/', { headers: { Accept: 'text/*' } });
```

...then we get inconsistent behaviour. For example, some browsers will merge the `Accept` value with the `accept` value set by httpism.

Since this is an easy mistake to make, we could either:

1. Silently convert all header names to lower case.
2. Throw an exception and remind the user to use lower case.
3. Delete any existing header with the same name in lower case, and send the header in the case the user specified.

Option 3 is my preferred route, because some servers are fussy about the case and will ignore headers in lower case. But that's a non-trivial change.

Thoughts @refractalize?

**Comment by refractalize** [comment]
I think the reason they're lower case is the same as node's reasoning - which is that HTTP headers are officially case-insensitive and Node needed to standardise on consistent casing - lower case seemed the least offensive.. at least I think that's why they did that. Maybe some comments here: https://github.com/nodejs/node-v0.x-archive/issues/1954

From the point of view of `httpism`, we want all middleware to refer to the same headers. We don't want one middleware, saying `Accept` and another saying `accept`.

Maybe we go for 1?

**Comment by refractalize** [comment]
I'm lower-casing all passed in headers, see aa8c0b0697e4ba56f186b14c55bc71bfe45b876b. Released in v1.14.0

**Comment by joshski** [comment]
Cool, cheers
